-- MySQL Script generated by MySQL Workbench
-- Wed May 24 16:27:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cunchain
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cunchain
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cunchain` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `cunchain` ;

-- -----------------------------------------------------
-- Table `cunchain`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cunchain`.`account` (
  `number` VARCHAR(18) NOT NULL COMMENT '账户统一编码',
  `org_number` VARCHAR(18) NOT NULL COMMENT '所在机构账户统一编码',
  `groups` VARCHAR(16) NULL COMMENT '用户分组，org, 机构用户',
  `account` VARCHAR(45) NOT NULL COMMENT '账户名',
  `password` VARCHAR(45) NULL COMMENT '账户密码',
  `phone_no` VARCHAR(45) NULL COMMENT '联系电话号码',
  `phone_no2` VARCHAR(45) NULL COMMENT '备用电话号码',
  `email` VARCHAR(45) NULL COMMENT '联系邮箱',
  `email2` VARCHAR(45) NULL COMMENT '备用邮箱',
  `address` VARCHAR(256) NULL COMMENT '通讯地址',
  `name` VARCHAR(45) NULL COMMENT '用户昵称／姓名／组织名称',
  `avatar` VARCHAR(256) NULL COMMENT '头像图片保存路径',
  `authenticated` TINYINT NULL COMMENT '是否实名认证',
  `register_time` DATETIME NULL COMMENT '登记日期',
  `token` BIGINT NOT NULL COMMENT '代币数',
  `credit` BIGINT NOT NULL COMMENT '积分数',
  `credit_cny_rate` DOUBLE NOT NULL COMMENT 'credit/CNY汇率', 
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC),
  UNIQUE INDEX `phone_no_UNIQUE` (`phone_no` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cunchain`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cunchain`.`user` (
  `number` VARCHAR(18) NOT NULL COMMENT '账户统一编码',
  `id_card` VARCHAR(18) NULL COMMENT '身份证号',
  `id_card_image_0` VARCHAR(256) NULL COMMENT '身份证正面图片保存路径',
  `id_card_image_1` VARCHAR(256) NULL COMMENT '身份证反面图片保存路径',
  `id_card_image_2` VARCHAR(256) NULL COMMENT '身份证手持图片保存路径',
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cunchain`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cunchain`.`organization` (
  `number` VARCHAR(18) NOT NULL COMMENT '账户统一编码',
  `contact_name` VARCHAR(45) NULL COMMENT '联系人姓名',
  `org_id` VARCHAR(18) NULL COMMENT '统一社会信用代码（18位）包含了组织机构代码（第9-17位）和税务登记证号码(第3-17位)。',
  `org_id_image` VARCHAR(256) NULL COMMENT '统一社会信用代码证图片保存路径',
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cunchain`.`anchor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cunchain`.`anchor` (
  `src_hash` VARCHAR(64) NOT NULL COMMENT '源链哈希',
  `des_hash` VARCHAR(64) NOT NULL COMMENT '目标链哈希',
  `type` VARCHAR(45) NOT NULL COMMENT '目标公链类型：btc，eth，…',
  `src_offset` VARCHAR(128) NOT NULL COMMENT '数据在源链中的位置\n',
  `des_offset` VARCHAR(128) NOT NULL COMMENT '数据在目标链中的位置\n',
  UNIQUE INDEX `src_offset_UNIQUE` (`src_offset` ASC),
  UNIQUE INDEX `des_offset_UNIQUE` (`des_offset` ASC),
  UNIQUE INDEX `src_hash_UNIQUE` (`src_hash` ASC),
  UNIQUE INDEX `des_hash_UNIQUE` (`des_hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cunchain`.`onchain_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cunchain`.`onchain_map` (
  `entry_hash` VARCHAR(128) NOT NULL,
  `file_hash` VARCHAR(128) NOT NULL,
  `file_name` VARCHAR(256) NULL,
  `file_size` INT NULL,
  `time` DATETIME NULL,
  `save_remote` TINYINT NULL,
  UNIQUE INDEX `entry_hash_UNIQUE` (`entry_hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cunchain`.`recharge_wx`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cunchain`.`recharge_wx` (
  `order_number` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '充值订单编号',
  `account_number` VARCHAR(18) NOT NULL COMMENT '账户统一编码',
  `prepay_id` VARCHAR(128) NULL COMMENT '预付订单ID',
  `bank_type` VARCHAR(45) NULL COMMENT '银行代码，参考微信',
  `time_start` DATETIME NOT NULL COMMENT '订单开始时间',
  `time_end` DATETIME NULL COMMENT '订单结束时间',
  `pay_state` VARCHAR(16) NOT NULL COMMENT '支付状态: SUCCESS—支付成功, REFUND—转入退款, NOTPAY—未支付, CLOSED—已关闭, REVOKED—已撤销（刷卡支付）, USERPAYING--用户支付中, PAYERROR--支付失败(其他原因，如银行返回失败)',
  `sale_state` VARCHAR(16) NOT NULL COMMENT '售卖状态: SUCCESS—购买成功, NOTSELL-未购买，FAILED—购买失败',
  `remark` VARCHAR(45) NULL COMMENT '交易备注',
  `amount` BIGINT NOT NULL COMMENT '金额',
  `product` VARCHAR(128) NULL COMMENT '产品类型',
  PRIMARY KEY (`order_number`),
  UNIQUE INDEX `order_number_UNIQUE` (`order_number` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;